GET http://localhost:3000/messages
###

POST http://localhost:3000/messages
Content-Type: application/json

{
    "name": "Jane",
    "message": "How are you?"
}

###

GET http://localhost:3000/messages/Tim